name = "NNlibBitSAD"
uuid = "3a97d706-ca6b-42d2-9a6c-df68ab7e4fa7"
authors = ["Kyle Daruwalla", "Soroosh Khoram", "University of Wisconsin-Madison PHARM Group"]
version = "0.1.0"

[deps]
BitSAD = "7f90e340-ca22-4a3e-a259-118ed254aff3"
Functors = "d9f16b24-f501-4c13-a1f2-28368ffc5196"
Ghost = "4f8f7498-1303-42e1-920c-5033445536df"
NNlib = "872c559c-99b0-510c-b3b7-b6c96a88d5cd"

[compat]
julia = "1.5"
