name = "NNlibBitSAD"
uuid = "3a97d706-ca6b-42d2-9a6c-df68ab7e4fa7"
authors = ["Kyle Daruwalla", "Soroosh Khoram", "University of Wisconsin-Madison PHARM Group"]
version = "0.1.0"

[deps]
Artifacts = "56f22d72-fd6d-98f1-02f0-08ddc0907c33"
BitSAD = "7f90e340-ca22-4a3e-a259-118ed254aff3"
Functors = "d9f16b24-f501-4c13-a1f2-28368ffc5196"
Ghost = "4f8f7498-1303-42e1-920c-5033445536df"
LazyArtifacts = "4af54fe1-eca0-43a8-85a7-787d91b784e3"
NNlib = "872c559c-99b0-510c-b3b7-b6c96a88d5cd"

[compat]
BitSAD = "0.1"
Functors = "0.2.8"
Ghost = "0.3"
julia = "1.6"
NNlib = "0.8"
